image: oven/bun:latest

cache:
  paths:
    - .output/public/

stages:
  - build
  - deploy

.default-setup: &default-setup
  tags:
    - docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      variables:
        CI_ENVIRONMENT_NAME: "staging"
        CI_ENVIRONMENT_URL: "https://www.t3s.es/"

    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        CI_ENVIRONMENT_NAME: "production"
        CI_ENVIRONMENT_URL: "https://www.topgroups.travel/"
  before_script:
    - echo "CI_ENVIRONMENT_URL=$CI_ENVIRONMENT_URL"
    - echo "NUXT_PUBLIC_SITE_URL=$CI_ENVIRONMENT_URL" > .env
    - cat .env
    - bun install

nuxt-build:
  extends:
    - .default-setup
  stage: build
  tags:
    - docker
  script:
    - echo "CI_ENVIRONMENT_URL=$CI_ENVIRONMENT_URL"
    - echo "NUXT_PUBLIC_SITE_URL=$NUXT_PUBLIC_SITE_URL"
    - cat .env
    - bun run generate
  artifacts:
    paths:
      - .output/public

deploy-staging:
  stage: deploy
  extends:
    - .default-setup
  needs:
    - nuxt-build
  script:
    - bun add -g wrangler # Install Wrangler globally with Bun
    - wrangler pages deploy .output/public --project-name=website-staging --branch=${CI_COMMIT_BRANCH}
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
  # only:
  #   - staging

deploy-production:
  stage: deploy
  extends:
    - .default-setup
  needs:
    - nuxt-build
  script:
    - bun add -g wrangler # Install Wrangler globally with Bun
    - wrangler pages deploy .output/public --project-name=website --branch=${CI_COMMIT_BRANCH}
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  # only:
  #   - main
