image: oven/bun:latest

cache:
  paths:
    - .output/public/

stages:
  - build
  - deploy

.default-setup: &default-setup
  tags:
    - docker
  before_script:
    - bun install
    - echo "CI_ENVIRONMENT_URL=$CI_ENVIRONMENT_URL"
    - echo "NUXT_PUBLIC_SITE_URL=$NUXT_PUBLIC_SITE_URL"
    - echo "NUXT_PUBLIC_SITE_URL=$CI_ENVIRONMENT_URL" > .env

nuxt-build:
  stage: build
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
    - if: $CI_COMMIT_BRANCH == "main"
  extends:
    - .default-setup
  script:
    - echo "CI_ENVIRONMENT_URL=$CI_ENVIRONMENT_URL"
    - echo "NUXT_PUBLIC_SITE_URL=$NUXT_PUBLIC_SITE_URL"
    - bun run generate
  artifacts:
    paths:
      - .output/public

deploy-staging:
  stage: deploy
  extends:
    - .default-setup
  needs:
    - nuxt-build
  environment:
    name: staging
    url: https://www.t3s.es/
  script:
    - bun add -g wrangler # Install Wrangler globally with Bun
    - wrangler pages deploy .output/public --project-name=website-staging --branch=${CI_COMMIT_BRANCH}
  only:
    - staging

deploy-production:
  stage: deploy
  extends:
    - .default-setup
  needs:
    - nuxt-build
  environment:
    name: production
    url: https://www.topgroups.travel/
  script:
    - bun add -g wrangler # Install Wrangler globally with Bun
    - wrangler pages deploy .output/public --project-name=website --branch=${CI_COMMIT_BRANCH}
  only:
    - main
