cache:
  paths:
    - node_modules/
    - .cache/
    - dist/

stages:
  - build
  - deploy

job-build:
  stage: build
  # variables:
  #   CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
  #   CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "main"
  # environment: "$CI_COMMIT_BRANCH"
  before_script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
    - export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
    - nvm install --lts
    - nvm use --lts
  script:
    - npm install
    - ./node_modules/.bin/gatsby build

job-deploy:
  stage: deploy
  variables:
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
    CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "main"
  # environment: "$CI_COMMIT_BRANCH"
  script:
    - npm install -g wrangler --unsafe-perm=true
    - wrangler pages publish ./dist --project-name=website --branch=main
  artifacts:
    paths:
      - dist
  # only:
  #   - main

# deploy:
#   stage: deploy
#   script:
#     - npm install
#     - ./node_modules/.bin/gatsby build
#     - npm install -g wrangler --unsafe-perm=true
#     - wrangler pages publish ./public --project-name=your-website --branch=main
#   artifacts:
#     paths:
#       - public
#   only:
#     - main
